### ISSUE TITLE
Backend returns 400 Axios error

### ISSUE THREAD

**Issue by aacitelli** [aacitelli/wowcraftingorders.com#23]
API sometimes returns 500 with an error like this in the logs:

```
{
  "textPayload": "AxiosError: Request failed with status code 400\n    at settle (/workspace/node_modules/axios/dist/node/axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (/workspace/node_modules/axios/dist/node/axios.cjs:2704:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:552:15)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "insertId": "639733a8000928e8b7d15425",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "wowtrade",
      "function_name": "app-prod",
      "region": "us-central1"
    }
  },
  "timestamp": "2022-12-12T13:59:04.600296Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "yheogrs3k9rt",
    "instance_id": "00c61b117cc9264d60a014d71221092ff1c42bade4a11423f3a335aa895106dd0908950ee0bad65bcae4c432df5c59be77abf20146125c53a9ea"
  },
  "logName": "projects/wowtrade/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/wowtrade/traces/1e3dbce25b68b59dff31b04eb670f3e3",
  "receiveTimestamp": "2022-12-12T13:59:04.795093336Z"
}
```

**Comment by aacitelli** [comment]
Was fixed among other fixes.
