### ISSUE TITLE
Backend returns 500 when updating timestamps

### ISSUE THREAD

**Issue by aacitelli** [aacitelli/wowcraftingorders.com#45]
Relevant Trace ID: xpl902v5hk0s

Relevant Error: 
```
{
  "textPayload": "Error: Unknown error updating buyer timestamps: TypeError: Cannot read properties of undefined (reading 'timestampSeconds')\n    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)\n    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)\n    at updateBuyerListingTimestampsService (/workspace/lib/services/buyerListingService.js:114:26)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "insertId": "63974bb80005700d63cabc12",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "app-prod",
      "region": "us-central1",
      "project_id": "wowtrade"
    }
  },
  "timestamp": "2022-12-12T15:41:44.356365Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "xpl902v5hk0s",
    "instance_id": "00c61b117c4001d744095bb5580ebba6cee33de29a95c6d3b68a943a9c74f685fcd5a4673b9e3233757e5798738d254541c9239d3135640bb571"
  },
  "logName": "projects/wowtrade/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/wowtrade/traces/ab8c33e2a9dc0e86a1abf1ed0db9916c",
  "receiveTimestamp": "2022-12-12T15:41:44.456184611Z"
}
```

**Comment by aacitelli** [comment]
Rectified. Axios Error Handling with async/await can be a little complicated and I messed it up the first time through, which was causing a crash on basically any authenticated route.
